import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ModalInitializer from '@/components/common/ModalInitializer';
import GlobalModal from '@/components/modal/GlobalModal';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ModalInitializer />
        <div id="app-root" className={`flex min-h-screen flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
          <GlobalModal />
        </div>
      </body>
    </html>
  );
}
